[build]
publish = "_site"
command = "eleventy"

[[redirects]]
from = "/2014/08/03/speaking-up.html"
to = "/2014/08/04/speaking-up/"

[[redirects]]
from = "/journal/speaking-up"
to = "/2014/08/04/speaking-up/"

[[redirects]]
from = "/journal/*"
to = "/writing/"
