[build]
  publish = "_site"
  command = "eleventy"


[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.2

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"


# REDIRECT and HEADERS examples

# Redirect rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

[[redirects]]
from = "/2014/08/03/speaking-up.html"
to = "/2014/08/04/speaking-up/"

[[redirects]]
from = "/journal/speaking-up"
to = "/2014/08/04/speaking-up/"

[[redirects]]
from = "/journal/*"
to = "/writing/"

[[redirects]]
from = "https://samkapila.com/thoughts/the-hard-truth-about-soft-skills"
to = "https://samkapila.com/2014/04/20/the-hard-truth-about-soft-skills/"

[[redirects]]
from = "https://samkapila.com/sharing/mcweek/"
to = "https://samkapila.com/2012/11/03/design-1-up-a-panel-at-mass-comm-week//"

[[redirects]]
from = "https://samkapila.com/2022/11/02/good-intentions-in-diversity-and-inclusion-work/feed.xml"
to = "https://samkapila.com/2022/11/02/good-intentions-in-diversity-and-inclusion-work/"



# The default HTTP status code is 301, but you can define a different one e.g.
# status = 302

# Headers rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[headers]]
#   Define which paths this specific [[headers]] block will cover.
#   for = "/*"

#[headers.values]
#   X-Frame-Options = "DENY"
#   X-XSS-Protection = "1; mode=block"
#   Content-Security-Policy = "frame-ancestors https://www.facebook.com"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# applied on a PER-DEPLOY basis.
